name: Self Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  terraform:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check Runner
        run: hostname

      - name: Check Terraform
        run: terraform version

      - name: Check AWS CLI
        run: aws --version

    
